fix: parsing issue with multiple sourceSets compilation
guqing/gradle-plugin-halo pull request #13
Opened 2024-05-09 08:32 UTC by ShiinaKin

Fixs #12 

@guqing 

```release-note
修复了多源集下无法解析正确目录导致 plugin-components.idx 无法生成的问题
```

2024-05-09 08:35 UTC, guqing commented on build.gradle
> +            url = version.findIndexOf { "-SNAPSHOT" } != -1 ? snapshotsRepoUrl : releasesRepoUrl
Hi @mashirot，感谢贡献，建议撤销对当前要解决问题无关的改动，一个 PR 建议只单独做一件事情

2024-05-09 08:36 UTC, guqing commented on gradle.properties
> +version=0.0.9-SNAPSHOT
同上

2024-05-09 08:36 UTC, guqing commented on build.gradle
> -    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jackjson"
同上

2024-05-09 08:37 UTC, mashirot commented on build.gradle
> +            url = version.findIndexOf { "-SNAPSHOT" } != -1 ? snapshotsRepoUrl : releasesRepoUrl
![image](https://github.com/halo-sigs/halo-gradle-plugin/assets/52254895/03b2145a-0cb7-4b88-9f7e-6e9d4ede0399)

2024-05-09 09:07 UTC, JohnNiang requested changes

2024-05-09 09:07 UTC, JohnNiang commented on src/main/java/run/halo/gradle/PluginComponentsIndexTask.java
> +        Path componentsIdxPath = Paths.get(classesFolderPath).resolve(FILEPATH);
这里我建议直接使用 `getProject().getLayout().getBuildDir().resolve("tmp")`，没有必要使用 classesDirs。

2024-05-09 09:32 UTC, JohnNiang reviewed
Hi @mashirot ,这里我认为使用 dir 更合适。

2024-05-09 09:32 UTC, JohnNiang commented on src/main/java/run/halo/gradle/PluginComponentsIndexTask.java
> +            .file("tmp").get().getAsFile().getPath();
```suggestion
            .dir("tmp").get().getAsFile().getPath();
```

2024-05-09 09:37 UTC, JohnNiang approved these changes
/approve

2024-05-09 10:11 UTC, JohnNiang commented
/ping @halo-sigs/halo

2024-05-09 10:19 UTC, guqing commented
> /ping @halo-sigs/halo

Hi @JohnNiang 帮忙测试一下 java 语言插件是否能在此改动下正确 work，现在没有时间

2024-05-13 03:15 UTC, guqing approved these changes
/lgtm

2024-05-13 03:16 UTC, JohnNiang approved these changes
Thank @mashirot  for your first contribution!

/lgtm

2024-05-13 03:16 UTC, merged